### ISSUE TITLE
Cooldown on movement after landing

### ISSUE THREAD

**Issue by trundler-dev** [apetavern/sbox-terryform#22]
We should have a cooldown on movement after jumping. This would prevent moving too soon after jumping, or jumping multiple times too quickly, which would make the movement feel more worm-like. Might be smart to scale the cooldown based on fall height.

**Comment by xezno** [comment]
Should be fixed now. I think the cooldown is a bit long but it can be tweaked pretty easily

**Comment by trundler-dev** [comment]
Is it possible to make it scale based on fall distance?

**Comment by xezno** [comment]
Should scale based on fall height now. Doesn't take it into account if you're jumping upwards, I can do that too though if you want

**Comment by trundler-dev** [comment]
Looks good!
