### ISSUE TITLE
Assign a client's pawn to their active worm

### ISSUE THREAD

**Issue by trundler-dev** [apetavern/sbox-terryform#27]
Active Worm logic should work, but I haven't figured out the best way to separate worms from each other and from other players. If you pull master you will see, after adding a bot, you are controlling both at once.

- [x] Implement client pawn swapping smoothly.
- [ ] Automatic camera should swap to active player's active worm upon the start of a turn.

**Comment by trundler-dev** [comment]
The client's pawn swaps to the proper worm upon its turn now, but we should still have the camera automatically track the active worm of the active player, not just the client's active worm. This should trigger upon the start of a turn.

**Comment by Matt9440** [comment]
Added base functionality in #42 
Will implement it in Turn soon.

**Comment by Matt9440** [comment]
Implemented in #47
