### ISSUE TITLE
Add a set of equippables called Tools

### ISSUE THREAD

**Issue by trundler-dev** [apetavern/sbox-terryform#28]
Tools differ from Weapons since they (generally) don't end a turn upon use, and sometimes can have custom logic like being able to use the same tool multiple times in a turn, etc. Tools logically should be similar to Weapons and may even descent from them in code if it makes the most sense too.

- [ ] Implement a Tools System

**Comment by Matt9440** [comment]
Do you have an idea for an example tool? I'm struggling to see what the use for them is - would they create something like a ladder to get yourself out if a crater? Would be useful to keep in mind when I implement the turn ending logic into weapons.

**Comment by trundler-dev** [comment]
Items like the grapple hook, jetpack, parachute, etc. would fit into this category. If it happens to work that they fit well under weapons, that is fine too :)

**Comment by trundler-dev** [comment]
All items should simply descend from weapons. Closing this.
