### ISSUE TITLE
Set Turn Timer to 5 seconds remaining if turn-ending weapon is fired

### ISSUE THREAD

**Issue by trundler-dev** [apetavern/sbox-terryform#29]
Ideally a weapon should have a bool that determines if it's use ends your turn. If that bool is true, StateDurationSeconds should be modified so the player's turn has only 5 seconds left **AFTER the weapon is finished firing + all projectiles have landed or destroyed**.

**Comment by xezno** [comment]
I believe this is done as of #31

**Comment by trundler-dev** [comment]
Tested and confirmed. Good work Matt!
