### ISSUE TITLE
Worms that haven't had an active turn yet aren't behaving properly

### ISSUE THREAD

**Issue by trundler-dev** [apetavern/sbox-terryform#34]
![20211124183350_1](https://user-images.githubusercontent.com/57276947/143321414-99dad307-8843-433d-8334-b59eefdd65b3.jpg)

Note this is the case for additional worms belonging to a player. The first worm spawned for any given player seems to load in just fine.

**Comment by Matt9440** [comment]
This happens because the additional worms controllers aren't simulated until it becomes their turn. Will look into a fix.

**Comment by xezno** [comment]
Fixed with #47
