### ISSUE TITLE
Player Inventory

### ISSUE THREAD

**Issue by Matt9440** [apetavern/sbox-terryform#41]
Players need to have a collection of weapons they can pick from at the start of each turn - this should also keep track of what weapons have been used / weapon ammo counts. Allow adding of weapons into this collection at runtime for things like weapon crates.

Related #28

**Comment by trundler-dev** [comment]
While this is being worked on we should lay the groundwork for customizable loadouts (allow players to choose what items to start with and how many) which could be something in GameConfig.
