### ISSUE TITLE
Hide weapons while walking

### ISSUE THREAD

**Issue by trundler-dev** [apetavern/sbox-terryform#43]
Weapons should be hidden while walking and the Worm pose should be set to none. Weapons should not be fireable while walking or in mid-air.

**Comment by Matt9440** [comment]
#eae14c1

GroundEntity doesn't set until CheckGroundEntity is called through Move again - which I think is why the weapon doesn't appear immediately after the worm lands.

**Comment by Matt9440** [comment]
Fixed as of https://github.com/apetavern/sbox-terryform/commit/e91d1283c0b6f5998cacc112e4d4d8b2c9f8622d
