### ISSUE TITLE
What should the game look like? Style, models, etc.

### ISSUE THREAD

**Issue by trundler-dev** [apetavern/sbox-terryform#5]
Before we make a lot of design decisions, we need to have an idea what we want the game to look like.

- [x] What should a **player's model** look like? Do we want it to be Terry? Look like Terry? Should it look like a Worm, or something else entirely?
- [x] Should the **environment** look realistic, animated, cartoonish, or something else?
- [x] Other considerations?

**Comment by xezno** [comment]
Would be pretty funny to have the worms themselves take on the same appearance as Terry, and if we're doing that it'd make sense to follow the rest of s&box's art style too imo

**Comment by Matt9440** [comment]
> 

That's how I imagine it to be too, remove the legs and stretch out the body to taper off like a worm.

**Comment by trundler-dev** [comment]
That sounds good to me. So using Terry's appearance and following s&box's art style, that would imply a realistic looking art environment.

If anyone knows a modeler (or is a modeler), it would be good to have them join the project.
