### ISSUE TITLE
Invisible terrain on the map around spawn points

### ISSUE THREAD

**Issue by trundler-dev** [apetavern/sbox-terryform#58]
![20211127201100_1](https://user-images.githubusercontent.com/57276947/143724091-bbc66fe3-1adb-4058-bd55-8c96e6edf98d.jpg)

**Comment by trundler-dev** [comment]
Likely some kind of collision box for the worms/players

**Comment by Matt9440** [comment]
If a worm has fallen through the floor, it's the worms bounding box. I've moved the spawn points up a bit on the projectile branch and haven't seen this since. Are you able to confirm?

**Comment by trundler-dev** [comment]
Yep, I think this is fixed in your branch. Closing this.

**Comment by trundler-dev** [comment]
Re-opening.

**Comment by Matt9440** [comment]
I think I have this fixed on my branch. I believe it's caused by the Pawn.Players respawn method calling base - it creates a hull for the player which we don't actually need, fixed by not calling base.Respawn().

Will leave the issue open until we can confirm it's fixed.

**Comment by Matt9440** [comment]
Haven't ran into this since.
