### ISSUE TITLE
UI System

### ISSUE THREAD

**Issue by trundler-dev** [apetavern/sbox-terryform#6]
We just need a basic UI system. The UI should work for most screen sizes. Standards should be put in place for our .scss files and how we decide when to create a new file.

- [x] Write a **simple UI**.
- [x] **Decide** and **document** how we should **handle .scss files** as described above.
- [x] Decide if we will use **HTML or C# exclusively, or a mixture**.

**Comment by Matt9440** [comment]
I personally prefer using C# exclusively when I write UI, with that said @xezno is the UI wizard so I'm happy to follow in his direction.

**Comment by xezno** [comment]
I don't mind, I think a mixture would be best though
