### ISSUE TITLE
After ending a turn with a weapon equipped, that same weapon does not behave properly in the hands of other worms.

### ISSUE THREAD

**Issue by trundler-dev** [apetavern/sbox-terryform#63]
**Steps to Reproduce**
- Start a game by adding a bot
- Switch turn to your own player
- Equip a weapon, use it, end turn and cycle to your next worm
- Equip the same weapon, and notice the weapon does not appear, but your original worm has the correct HoldPose.

**Comment by Matt9440** [comment]
Fixed in my branch
